### ISSUE TITLE
Cannot promisify node-serialport

### ISSUE THREAD

**Issue by endorama** [nodegit/promisify-node#8] opened 2015-02-10 11:52 UTC
Hello, I'm trying to use this module bu I'm having some weird time with node-serialport.

The problems seems to be the SerialPort constructor, which accepts a callback that is correctly promisified but not resolved ( at least this is what is seems to me ).

```javascript
var promisify = require("promisify-node");
var serialport = promisify('serialport');
var SerialPort = serialport.SerialPort;


var port = "/dev/ttyACM0";
var serial_port = new SerialPort(port, {
    baudrate: 57600,
    parser: serialport.parsers.readline("\n")
});

console.log(serial_port)
// Promise {then: function, state: null, isFulfilled: function, isRejected: function, isPending: function…}
serial_port
  .then(function() {console.log(arguments, serial_port)})
  // [undefined] Promise {then: function, state: null, isFulfilled: function, isRejected: function, isPending: function…}
```

In this situation I'm not able to call methods on the serial_port object. Any hint on how to solve this? Thanks in advance.

**Comment by maxkorp** [comment] 2015-02-10 20:57
It looks like the constructor is a native module, which doesnt export its args etc in a visible way, so promisify-node can't promisify it. 

Try doing something like this
```
var serialport = promisify('serialport');
var SerialPort = promisify(serialport.SerialPort);
```

**Comment by endorama** [comment] 2015-02-18 17:00
I tried this snippet, but the console.log inside then() is not executed. No error is shown, the program simply exit and the end of execution. Does this mean that promisify `serialport` module is not possible?

```js
var promisify = require("promisify-node");
var serialport = promisify('serialport');
var SerialPort = promisify(serialport.SerialPort);

var port = "/dev/ttyACM0";
var serial_port = new SerialPort(port, {
    baudrate: 57600,
    parser: serialport.parsers.readline("\n")
});

console.log(serial_port)
// Promise {then: function, state: null, isFulfilled: function, isRejected: function, isPending: function…}
serial_port
  .then(function() {console.log(arguments, serial_port)})
```

**Comment by maxkorp** [comment] 2015-02-19 15:49
Should be workable. Try adding a `.catch` to the end and seeing if you get an error
```js
serial_port
  .then(function() {console.log(arguments, serial_port)})
  .catch(function(reason) {console.log(reason)});
```
You can also try looking at `serial_port.state`, or using the accessors `.isRejected()`, `.isFulfilled()`, and `.isPending()` to see whats going on.

**Comment by maxkorp** [comment] 2015-02-19 16:20
Ah found it. It was pending forever. It turns out that A) You don't need the second promisify (so this should be fine)
```js
var promisify = require("promisify-node");
var serialport = promisify('serialport');
var SerialPort = serialport.SerialPort;
```

The issue is that it's only getting 2 arguments in from you, and so it passes the callback for the third, which just gets used as a truthy value, rather than being called as the callback, so you need to pass the argument for openImmediately (the third of four in a typical serialport construction) as whichever you want.

```js
var port = "/dev/ttyACM0";
var serial_port = new SerialPort(port, {
    baudrate: 57600,
    parser: serialport.parsers.readline("\n")
}, 
true); //this is the important one. 
```

if youd like to be able to skip it, you can roll a custom promise on top
```js
var promisify = require("promisify-node");
var serialport = promisify('serialport');
var SerialPort = function(port, opts, openImmediately) {
  openImmediately = openImmediately || false;
  opts = opts || {};
  return new serialport.SerialPort(port, opts, openImmediately);
};

var port = "/dev/ttyACM0";
var serial_port = SerialPort(port, {
    baudrate: 57600,
    parser: serialport.parsers.readline("\n")
}, true);
```

Regarding the other methods, it may have tried to promisify `.on`, which either is or works like an event emitter, so that might need custom promisification as well. 

I'm going to make an issue for promisify requiring you to pass in all of the options with constructors, but I'm going to close this now that its figured out. Feel free to post here still though if there's still an issue for you.

**Closed by maxkorp** 2015-02-19 16:20 UTC

**Comment by endorama** [comment] 2015-02-19 20:51
Thanks for the clarification! :) I've already found a workaround for this but I'll try the solution you propose.

If I still have issues I'll report them here.

Thanks for your help and your time.
Cheers
